version: "3"

# https://taskfile.dev/usage/#env-files
dotenv: [".env.local", ".env"]

vars:
    # https://taskfile.dev/reference/templating/
    BASE_URL: '{{.TASK_BASE_URL | default .COMPOSE_SERVER_DOMAIN | default .COMPOSE_DOMAIN | default "http://tidy-feedback-collector.local.itkdev.dk"}}'
    DOCKER_COMPOSE: '{{.TASK_DOCKER_COMPOSE | default "docker compose"}}'

tasks:
    compose:
        desc: Run docker compose command
        cmds:
            - "{{.DOCKER_COMPOSE}} {{.CLI_ARGS}}"

    compose-up:
        desc: Start Docker containers
        cmds:
            - "{{.DOCKER_COMPOSE}} up -d"

    composer:
        desc: Run composer command
        cmds:
            - "{{.DOCKER_COMPOSE}} exec phpfpm composer {{.CLI_ARGS}}"

    console:
        desc: Run Symfony console command
        cmds:
            - "{{.DOCKER_COMPOSE}} exec phpfpm bin/console {{.CLI_ARGS}}"

    coding-standards-php-check:
        desc: Check PHP coding standards (PHP CS Fixer)
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm phpfpm vendor/bin/php-cs-fixer fix --dry-run --diff"

    coding-standards-php-apply:
        desc: Apply PHP coding standards (PHP CS Fixer)
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm phpfpm vendor/bin/php-cs-fixer fix"

    coding-standards-twig-check:
        desc: Check Twig coding standards
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm phpfpm vendor/bin/twig-cs-fixer lint"

    coding-standards-twig-apply:
        desc: Apply Twig coding standards
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm phpfpm vendor/bin/twig-cs-fixer lint --fix"

    coding-standards-markdown-check:
        desc: Check Markdown coding standards
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm markdownlint --dot '**/*.md' --ignore vendor --ignore node_modules"

    coding-standards-markdown-apply:
        desc: Apply Markdown coding standards
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm markdownlint --dot --fix '**/*.md' --ignore vendor --ignore node_modules"

    coding-standards-prettier-check:
        desc: Check Prettier coding standards (YAML, JS, etc.)
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm prettier --check ."

    coding-standards-prettier-apply:
        desc: Apply Prettier coding standards (YAML, JS, etc.)
        cmds:
            - "{{.DOCKER_COMPOSE}} run --rm prettier --write ."

    ci:
        desc: Run all coding standards checks
        cmds:
            - task: coding-standards-php-check
            - task: coding-standards-twig-check
            - task: coding-standards-markdown-check
            - task: coding-standards-prettier-check
